"""Provider-neutral financial data contracts and gateways.

The data gateway is the anti-corruption boundary between vendor payloads and
Tradex features.  Provider adapters may change independently; callers consume
versioned canonical models instead of DataFrames or vendor field names.
"""

from .contracts import (
    AShareUniverseQuoteV1,
    AShareUniverseSnapshotV1,
    BoardLeaderSnapshotV1,
    BoardLeaderSnapshotV2,
    BoardLeaderV1,
    BoardLeaderV2,
    ContractMetadata,
    DragonTigerSeriesV1,
    DragonTigerTradeV1,
    EtfQuoteSeriesV1,
    EtfQuoteV1,
    IndexQuoteV1,
    IndexIntradaySeriesV1,
    IndexMinuteQuoteV1,
    IntradayMinutePointV1,
    IntradayMinuteSeriesV1,
    LeaderQuoteSeriesV1,
    LeaderQuoteV1,
    LimitEventSeriesV1,
    LimitEventTradeStatusV1,
    LimitUpEventV1,
    LimitUpStatusSeriesV1,
    LimitUpStatusV1,
    MarketOverviewV1,
    MarketBreadthV1,
    MarketStateV1,
    MarketTurnoverV1,
    OpeningAuctionSnapshotV1,
    OpeningAuctionMarketV1,
    OHLCVBarV1,
    OHLCVSeriesV1,
    ParticipationIndexV1,
    QualityStatus,
    QuoteSnapshotV1,
    SectorQuoteSeriesV1,
    SectorQuoteV1,
    SectorFundFlowIntradayV1,
    SectorFundFlowMinuteV1,
    StockFundFlowSeriesV1,
    StockFundFlowV1,
    StockSectorProfileSeriesV1,
    StockSectorProfileV1,
)
from .daily_review import fetch_dragon_tiger_day, fetch_stock_fund_flow_day
from .stock_selection import fetch_daily_stock_factor_snapshot
from .instrument_taxonomy import fetch_stock_relationship_source_bundle
from .stock_selection_contracts import (
    DailyStockFactorSnapshotV1,
    DailyStockFactorV1,
    StockFactorCoverageV1,
)
from .auctions import (
    fetch_opening_auction_market,
    fetch_opening_auction_snapshot,
    opening_auction_to_legacy_payload,
)
from .etfs import etf_quotes_to_legacy_records, fetch_etf_quotes
from .leadership import (
    board_leader_snapshot_to_legacy_payload,
    fetch_board_leader_snapshot,
    fetch_leader_quotes,
    fetch_stock_sector_profiles,
    leader_quotes_to_legacy_records,
    stock_sector_profiles_to_legacy_records,
)
from .limit_events import (
    fetch_limit_up_events,
    fetch_limit_up_status,
    limit_event_series_to_component_metadata,
    limit_event_series_to_legacy_records,
)
from .market import fetch_market_overview, market_overview_to_legacy_payload
from .intraday import (
    IntradayMinuteCache,
    fetch_intraday_minute_series,
    fetch_intraday_minute_series_batch,
    fetch_intraday_minute_series_batch_partial,
    intraday_minute_to_legacy_payload,
)
from .market_universe import fetch_a_share_universe_snapshot
from .index_intraday import fetch_index_intraday_series
from .market_structure import (
    fetch_market_breadth_snapshot,
    fetch_sector_quotes,
    market_breadth_to_legacy_records,
    metadata_to_component_status,
    sector_quotes_to_legacy_records,
)
from .securities import (
    fetch_ohlcv_series,
    fetch_quote_snapshot,
    ohlcv_series_to_legacy_records,
    quote_snapshot_to_legacy_records,
)
from .sector_flow import (
    SectorFundFlowBackfillCache,
    SectorFundFlowStore,
    fetch_sector_intraday_fund_flow,
    fetch_sector_intraday_fund_flow_backfill,
)

__all__ = [
    "AShareUniverseQuoteV1",
    "AShareUniverseSnapshotV1",
    "BoardLeaderSnapshotV1",
    "BoardLeaderSnapshotV2",
    "BoardLeaderV1",
    "BoardLeaderV2",
    "ContractMetadata",
    "DragonTigerSeriesV1",
    "DragonTigerTradeV1",
    "DailyStockFactorSnapshotV1",
    "DailyStockFactorV1",
    "EtfQuoteSeriesV1",
    "EtfQuoteV1",
    "IndexQuoteV1",
    "IndexIntradaySeriesV1",
    "IndexMinuteQuoteV1",
    "IntradayMinuteCache",
    "IntradayMinutePointV1",
    "IntradayMinuteSeriesV1",
    "LeaderQuoteSeriesV1",
    "LeaderQuoteV1",
    "LimitEventSeriesV1",
    "LimitEventTradeStatusV1",
    "LimitUpEventV1",
    "LimitUpStatusSeriesV1",
    "LimitUpStatusV1",
    "MarketOverviewV1",
    "MarketBreadthV1",
    "MarketStateV1",
    "MarketTurnoverV1",
    "OpeningAuctionMarketV1",
    "OpeningAuctionSnapshotV1",
    "OHLCVBarV1",
    "OHLCVSeriesV1",
    "ParticipationIndexV1",
    "QualityStatus",
    "QuoteSnapshotV1",
    "SectorQuoteSeriesV1",
    "SectorQuoteV1",
    "SectorFundFlowIntradayV1",
    "SectorFundFlowMinuteV1",
    "SectorFundFlowBackfillCache",
    "SectorFundFlowStore",
    "StockFundFlowSeriesV1",
    "StockFundFlowV1",
    "StockFactorCoverageV1",
    "StockSectorProfileSeriesV1",
    "StockSectorProfileV1",
    "board_leader_snapshot_to_legacy_payload",
    "fetch_board_leader_snapshot",
    "fetch_a_share_universe_snapshot",
    "fetch_dragon_tiger_day",
    "fetch_daily_stock_factor_snapshot",
    "fetch_stock_relationship_source_bundle",
    "fetch_etf_quotes",
    "fetch_leader_quotes",
    "fetch_limit_up_events",
    "fetch_limit_up_status",
    "fetch_market_breadth_snapshot",
    "fetch_market_overview",
    "fetch_intraday_minute_series",
    "fetch_intraday_minute_series_batch",
    "fetch_intraday_minute_series_batch_partial",
    "fetch_index_intraday_series",
    "fetch_opening_auction_snapshot",
    "fetch_opening_auction_market",
    "fetch_ohlcv_series",
    "fetch_quote_snapshot",
    "fetch_sector_quotes",
    "fetch_sector_intraday_fund_flow",
    "fetch_sector_intraday_fund_flow_backfill",
    "fetch_stock_sector_profiles",
    "fetch_stock_fund_flow_day",
    "leader_quotes_to_legacy_records",
    "etf_quotes_to_legacy_records",
    "limit_event_series_to_component_metadata",
    "limit_event_series_to_legacy_records",
    "market_breadth_to_legacy_records",
    "market_overview_to_legacy_payload",
    "intraday_minute_to_legacy_payload",
    "metadata_to_component_status",
    "ohlcv_series_to_legacy_records",
    "opening_auction_to_legacy_payload",
    "quote_snapshot_to_legacy_records",
    "sector_quotes_to_legacy_records",
    "stock_sector_profiles_to_legacy_records",
]
