from pathlib import Path
root=Path('work/macd_j_v5_20260918');(root/'before').mkdir(parents=True,exist_ok=True)
files=['stock_selection/macd_rules.py','stock_selection/macd_j.py','stock_selection/contracts.py','stock_selection/intraday_macd_j.py','stock_selection/strategies.py','stock_selection/intraday_increment.py','stock_selection/insights.py','dashboard/watch/app.js','dashboard/watch/index.html']
for f in files:
 p=Path('tradex/src/tradex')/f;(root/'before'/str(p).replace('\\','__').replace('/','__')).write_bytes(p.read_bytes())
p=Path('docs/intraday-macd-j.md');(root/'before'/'docs__intraday-macd-j.md').write_bytes(p.read_bytes())
p=Path('tradex/src/tradex/stock_selection/macd_rules.py');s=p.read_text(encoding='utf-8').replace('def v4_signal(points):','def v4_signal(points, *, max_j_lead=1):').replace('if len(points) < 4:','if max_j_lead not in (1, 2):\n        raise ValueError("unsupported J lead window")\n    if len(points) < max_j_lead + 3:').replace('for i in (len(js)-2, len(js)-1)','for i in range(len(js)-1-max_j_lead, len(js))');p.write_text(s,encoding='utf-8')
p=Path('tradex/src/tradex/stock_selection/macd_j.py');s=p.read_text(encoding='utf-8').replace('v4_signal(points)[0]','v4_signal(points, max_j_lead=2)[0]').replace('version="v4"','version="v5"').replace('{"v1", "v2", "v3", "v4"}','{"v1", "v2", "v3", "v4", "v5"}').replace('version == "v4"','version in {"v4", "v5"}').replace('kind, index = v4_signal(points)','kind, index = v4_signal(points, max_j_lead=2 if version == "v5" else 1)').replace('excluded["no_v4_signal"]','excluded["no_current_signal"]')
s=s.replace('signal_rule="strict_cross_v4" if kind == "confirmed" else "pending_cross_v4",','signal_rule=f"strict_cross_{version}" if kind == "confirmed" else f"pending_cross_{version}",').replace('signal_group="same_day" if gap == 0 else "prior_1_session",','signal_group="same_day" if gap == 0 else "prior_2_sessions" if version == "v5" else "prior_1_session",')
s=s.replace('"正式入选：昨天 DIF≤DEA，今天 DIF>DEA；J 当天或前一交易日由下降/走平转为上升，今天仍上升。",','("正式入选：昨天 DIF≤DEA，今天 DIF>DEA；J 当天或此前1～2个交易日由下降/走平转为上升，今天仍上升。" if version == "v5" else\n             "正式入选：昨天 DIF≤DEA，今天 DIF>DEA；J 当天或前一交易日由下降/走平转为上升，今天仍上升。"),');p.write_text(s,encoding='utf-8')
p=Path('tradex/src/tradex/stock_selection/contracts.py');s=p.read_text(encoding='utf-8').replace('"strict_cross_v4", "pending_cross_v4"]','"strict_cross_v4", "pending_cross_v4", "strict_cross_v5", "pending_cross_v5"]').replace('"prior_3_sessions", "prior_1_session"]','"prior_3_sessions", "prior_1_session", "prior_2_sessions"]')
s=s.replace('self.signal_rule in {"strict_cross_v4", "pending_cross_v4"}', 'self.signal_rule in {"strict_cross_v4", "pending_cross_v4", "strict_cross_v5", "pending_cross_v5"}').replace('kind, index = v4_signal(self.evidence)','kind, index = v4_signal(self.evidence, max_j_lead=2 if self.signal_rule.endswith("v5") else 1)').replace('expected = "confirmed" if self.signal_rule == "strict_cross_v4" else "pending_cross"','expected = "confirmed" if self.signal_rule.startswith("strict_cross_") else "pending_cross"').replace('("same_day" if self.gap_sessions == 0 else "prior_1_session")','("same_day" if self.gap_sessions == 0 else "prior_2_sessions" if self.signal_rule.endswith("v5") else "prior_1_session")')
s=s.replace('"macd-j-upturn-main-board.v4"]','"macd-j-upturn-main-board.v4", "macd-j-upturn-main-board.v5"]').replace('"v4": "strict_cross_v4"}', '"v4": "strict_cross_v4", "v5": "strict_cross_v5"}').replace('c.signal_rule != "pending_cross_v4"','c.signal_rule != rule.replace("strict_cross_", "pending_cross_")').replace('rule != "strict_cross_v4"','rule not in {"strict_cross_v4", "strict_cross_v5"}')
p.write_text(s,encoding='utf-8')
p=Path('tradex/src/tradex/stock_selection/intraday_macd_j.py');s=p.read_text(encoding='utf-8').replace('SCREEN_VERSION = "macd-j-upturn-main-board.v4"','SCREEN_VERSION = "macd-j-upturn-main-board.v5"').replace('v4_signal(points[-5:] + [projected])','v4_signal(points[-5:] + [projected], max_j_lead=2)').replace('excluded["no_v4_signal"]','excluded["no_current_signal"]').replace('"signal_group": "同日拐头" if turn == 5 else "前一交易日拐头",','"signal_group": "同日拐头" if turn == 5 else "此前1～2个交易日拐头",')
s=s.replace('result = (read_archived_strategy_result(day, "macd-j-upturn-main-board", strategy_version="v4")','result = (read_archived_strategy_result(day, "macd-j-upturn-main-board", strategy_version="v5")\n              or read_archived_strategy_result(day, "macd-j-upturn-main-board", strategy_version="v4")').replace('candidate.signal_rule == "pending_cross_v4"','candidate.signal_rule in {"pending_cross_v4", "pending_cross_v5"}').replace('"前一交易日拐头" if candidate.signal_group == "prior_1_session" else "此前 1～3 日拐头",','"前一交易日拐头" if candidate.signal_group == "prior_1_session" else\n                            "此前1～2个交易日拐头" if candidate.signal_group == "prior_2_sessions" else "此前 1～3 日拐头",');p.write_text(s,encoding='utf-8')
p=Path('tradex/src/tradex/stock_selection/strategies.py');s=p.read_text(encoding='utf-8').replace('strategy_id="macd-j-upturn-main-board",\n        strategy_version="v4",','strategy_id="macd-j-upturn-main-board",\n        strategy_version="v5",');p.write_text(s,encoding='utf-8')
p=Path('tradex/src/tradex/stock_selection/intraday_increment.py');s=p.read_text(encoding='utf-8').replace('version="v4"','version="v5"').replace('"macd-j-upturn-main-board.v4"}', '"macd-j-upturn-main-board.v4", "macd-j-upturn-main-board.v5"}');p.write_text(s,encoding='utf-8')
p=Path('tradex/src/tradex/stock_selection/insights.py');s=p.read_text(encoding='utf-8').replace('candidate.get("signal_rule") == "strict_cross_v4"','candidate.get("signal_rule") in {"strict_cross_v4", "strict_cross_v5"}');p.write_text(s,encoding='utf-8')
